/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import Controlador.Controlador;
import Modelo.Administrador;
import Modelo.Clientes;
import Modelo.Documento;
import Modelo.Empleado;
import Modelo.MateriaPrima;
import Modelo.Productos;
import Modelo.Proveedor;
import Modelo.SqlAdministrador;
import Modelo.SqlCuentas;
import Modelo.SqlEmpleado;
import Modelo.Ventas;

/**
 *
 * @author Usuario
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        CrearComponentes();
    }

    private void CrearComponentes() {
        Empleado empleado = new Empleado();
        Administrador administrador = new Administrador();
        Clientes clientes = new Clientes();
        Proveedor proveedor = new Proveedor();
        SqlAdministrador sqlAdministrador = new SqlAdministrador();
        SqlEmpleado sqlEmpleado = new SqlEmpleado();
        SqlCuentas sqlCuentas = new SqlCuentas();
        VistaRegistro vistaR = new VistaRegistro(this, rootPaneCheckingEnabled);
        Login login = new Login();
        Documento documento = new Documento();

        //Admin
        MateriaPrima materiaPrima = new MateriaPrima();
        Productos productos = new Productos();
        Ventas ventas = new Ventas();
        VistaAdministrador vistaA = new VistaAdministrador();
        VistaEmpleado vistaE = new VistaEmpleado();

        Controlador controlador = new Controlador(administrador, empleado, clientes, proveedor,
                sqlAdministrador, sqlEmpleado, login, materiaPrima, productos, ventas, vistaA,
                vistaE, vistaR, sqlCuentas, this, documento);

        controlador.Iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        pn_home = new javax.swing.JPanel();
        btn_user = new javax.swing.JButton();
        lb_usuario = new javax.swing.JLabel();
        lb_administrador = new javax.swing.JLabel();
        lb_derechos = new javax.swing.JLabel();
        btn_admin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_salir = new javax.swing.JButton();
        lb_sistemaPanaderia = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pn_home.setBackground(new java.awt.Color(55, 104, 167));
        pn_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User_185.png"))); // NOI18N
        btn_user.setContentAreaFilled(false);
        btn_user.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_user.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User_185.png"))); // NOI18N
        btn_user.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User_194.png"))); // NOI18N
        btn_user.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pn_home.add(btn_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 230, 220));

        lb_usuario.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lb_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lb_usuario.setText("USUARIO");
        pn_home.add(lb_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 118, 51));

        lb_administrador.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lb_administrador.setForeground(new java.awt.Color(255, 255, 255));
        lb_administrador.setText("ADMINISTRADOR");
        pn_home.add(lb_administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, 40));

        lb_derechos.setBackground(new java.awt.Color(0, 0, 0));
        lb_derechos.setText("  © 2021 Grupo #5 - Sistemas-Procesos-Proyecto. Todos los derechos reservados");
        pn_home.add(lb_derechos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 500, 30));

        btn_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Admin_185.png"))); // NOI18N
        btn_admin.setContentAreaFilled(false);
        btn_admin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_admin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Admin_185.png"))); // NOI18N
        btn_admin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Admin_194.png"))); // NOI18N
        btn_admin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pn_home.add(btn_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 220, 220));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/P_Salir.Oscuro.png"))); // NOI18N
        btn_salir.setToolTipText("salir");
        btn_salir.setContentAreaFilled(false);
        btn_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/P_Salir.Oscuro.png"))); // NOI18N
        btn_salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/P_Salir.Claro.png"))); // NOI18N
        btn_salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        lb_sistemaPanaderia.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        lb_sistemaPanaderia.setForeground(new java.awt.Color(255, 255, 255));
        lb_sistemaPanaderia.setText("SISTEMA PANADERÍA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(lb_sistemaPanaderia)
                .addGap(136, 136, 136)
                .addComponent(btn_salir)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_salir)
                    .addComponent(lb_sistemaPanaderia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_home.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 770, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_admin;
    public javax.swing.JButton btn_salir;
    public javax.swing.JButton btn_user;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_administrador;
    private javax.swing.JLabel lb_derechos;
    private javax.swing.JLabel lb_sistemaPanaderia;
    private javax.swing.JLabel lb_usuario;
    public javax.swing.JPanel pn_home;
    // End of variables declaration//GEN-END:variables
}
