/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import EstructuraLista.ListaLineal;
import EstructuraLista.Nodo;
import EstructuraLista.Productos;

/**
 *
 * @author Armando Perugachi
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    ListaLineal lista;
    Productos productos;

    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        lista = new ListaLineal();

        lista.ingresarPrueba(new Productos("MICLG", "MICROONDAS", 4, 200.00, 2));
        lista.ingresarPrueba(new Productos("REFDUREX15", "REFRIGRERADORA", 8, 800.00, 2));
        lista.ingresarPrueba(new Productos("LICOSTER", "LICUADORA", 9, 90.00, 3));
        lista.ingresarPrueba(new Productos("BICIMX21", "BICICLETA", 12, 500.00, 3));
        lista.ingresarPrueba(new Productos("COCIND5", "COCINA", 5, 600.00, 3));
        lista.ingresarPrueba(new Productos("TVTCL40", "TELEVISION", 12, 700.00, 4));
        lista.ingresarPrueba(new Productos("TVTCL40", "TELEVISION", 12, 7.00, 4));
        lista.ingresarPrueba(new Productos("TVTCL40", "TELEVISION", 12, 70.00, 4));
        lista.ingresarPrueba(new Productos("TVTCL40", "TELEVISION", 12, 721.00, 4));
        lista.ingresarPrueba(new Productos("TVTCL40", "TELEVISION", 12, 621.00, 4));
        lista.ingresarPrueba(new Productos("TVTCL40", "TELEVISION", 12, 21.00, 4));
        lista.ingresarPrueba(new Productos("TVTCL40", "TELEVISION", 12, 1721.00, 4));
        lista.ingresarPrueba(new Productos("TVTCL40", "TELEVISION", 12, 1.00, 4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btIngresarPrueba = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtMinimo = new javax.swing.JTextField();
        btRetirarInicio = new javax.swing.JToggleButton();
        btNElementos = new javax.swing.JToggleButton();
        btIngresarFinal = new javax.swing.JToggleButton();
        btIngresarInicio = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCampoTexto = new javax.swing.JTextArea();
        btUltimo = new javax.swing.JToggleButton();
        btFrente = new javax.swing.JToggleButton();
        btReporte = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Estructura de datos lista");
        jpInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Realizado por: Perugachi Luis");
        jpInicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btIngresarPrueba.setBackground(new java.awt.Color(247, 246, 251));
        btIngresarPrueba.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btIngresarPrueba.setText("Ingresar Prueba");
        btIngresarPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarPruebaActionPerformed(evt);
            }
        });
        jpInicio.add(btIngresarPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 190, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Nombre: ");
        jpInicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Precio: ");
        jpInicio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Código: ");
        jpInicio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Mínimo: ");
        jpInicio.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Cantidad: ");
        jpInicio.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jpInicio.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 260, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jpInicio.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 260, -1));

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jpInicio.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 260, -1));

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jpInicio.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 260, -1));

        txtMinimo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jpInicio.add(txtMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 260, -1));

        btRetirarInicio.setBackground(new java.awt.Color(247, 246, 251));
        btRetirarInicio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btRetirarInicio.setText("Retirar Primer Elemento");
        btRetirarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetirarInicioActionPerformed(evt);
            }
        });
        jpInicio.add(btRetirarInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 190, -1));

        btNElementos.setBackground(new java.awt.Color(247, 246, 251));
        btNElementos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btNElementos.setText("Número de elementos ");
        btNElementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNElementosActionPerformed(evt);
            }
        });
        jpInicio.add(btNElementos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        btIngresarFinal.setBackground(new java.awt.Color(247, 246, 251));
        btIngresarFinal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btIngresarFinal.setText("Ingresar al Final");
        btIngresarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarFinalActionPerformed(evt);
            }
        });
        jpInicio.add(btIngresarFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 190, -1));

        btIngresarInicio.setBackground(new java.awt.Color(247, 246, 251));
        btIngresarInicio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btIngresarInicio.setText("Ingresar al Inicio");
        btIngresarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarInicioActionPerformed(evt);
            }
        });
        jpInicio.add(btIngresarInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 190, -1));

        txtCampoTexto.setColumns(20);
        txtCampoTexto.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtCampoTexto.setRows(5);
        jScrollPane1.setViewportView(txtCampoTexto);

        jpInicio.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 370, 230));

        btUltimo.setBackground(new java.awt.Color(247, 246, 251));
        btUltimo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btUltimo.setText("Ultimo");
        btUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUltimoActionPerformed(evt);
            }
        });
        jpInicio.add(btUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 90, -1));

        btFrente.setBackground(new java.awt.Color(247, 246, 251));
        btFrente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btFrente.setText("Frente");
        btFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFrenteActionPerformed(evt);
            }
        });
        jpInicio.add(btFrente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 90, -1));

        btReporte.setBackground(new java.awt.Color(247, 246, 251));
        btReporte.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btReporte.setText("Reporte");
        btReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReporteActionPerformed(evt);
            }
        });
        jpInicio.add(btReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 190, -1));

        getContentPane().add(jpInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIngresarPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarPruebaActionPerformed
        try {
            String codigo = this.txtCodigo.getText();
            String nombre = this.txtNombre.getText();
            int cantidad = Integer.valueOf(this.txtCantidad.getText());
            double precio = Double.parseDouble(this.txtPrecio.getText());
            int minimo = Integer.parseInt(this.txtMinimo.getText());
            productos = new Productos(codigo, nombre, cantidad, precio, minimo);

            this.txtCampoTexto.setText(lista.ingresarPrueba(productos));
            LimpiarCajas();
        } catch (NumberFormatException e) {
            this.txtCampoTexto.setText("Por favor digite un número\nen los campos cantidad, precio, mínimo");
        }

    }//GEN-LAST:event_btIngresarPruebaActionPerformed

    private void btRetirarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetirarInicioActionPerformed
        try {
            if (!lista.listaVacia()) {
                productos = (Productos) lista.retirarPrimerNodo();
                this.txtCampoTexto.setText("Se ha retirado el primer elemento: \n" + productos);
            } else {
                this.txtCampoTexto.setText("No hay elementos en la lista");
            }
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("Por favor cree la lista de elementos");
        }
    }//GEN-LAST:event_btRetirarInicioActionPerformed

    private void btNElementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNElementosActionPerformed
        try {
            this.txtCampoTexto.setText("El número de elementos es: " + lista.getNumeroNodos());
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("Por favor asegurese de crear la lista de elementos");
        }
    }//GEN-LAST:event_btNElementosActionPerformed

    private void btIngresarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarFinalActionPerformed
        try {
            String codigo = this.txtCodigo.getText();
            String nombre = this.txtNombre.getText();
            int cantidad = Integer.valueOf(this.txtCantidad.getText());
            double precio = Double.parseDouble(this.txtPrecio.getText());
            int minimo = Integer.parseInt(this.txtMinimo.getText());
            productos = new Productos(codigo, nombre, cantidad, precio, minimo);

            this.txtCampoTexto.setText(lista.ingresarFinal(productos));
            LimpiarCajas();
        } catch (NumberFormatException e) {
            this.txtCampoTexto.setText("Por favor digite un número\nen los campos cantidad, precio, mínimo");
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("Por favor cree la lista para ingresar elementos");
        }
    }//GEN-LAST:event_btIngresarFinalActionPerformed

    private void btIngresarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarInicioActionPerformed
        try {
            String codigo = this.txtCodigo.getText();
            String nombre = this.txtNombre.getText();
            int cantidad = Integer.valueOf(this.txtCantidad.getText());
            double precio = Double.parseDouble(this.txtPrecio.getText());
            int minimo = Integer.parseInt(this.txtMinimo.getText());
            productos = new Productos(codigo, nombre, cantidad, precio, minimo);

            this.txtCampoTexto.setText(lista.ingresarInicio(productos));
            LimpiarCajas();
        } catch (NumberFormatException e) {
            this.txtCampoTexto.setText("Por favor digite un número\nen los campos cantidad, precio, mínimo");
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("Por favor cree la lista para ingresar elementos");
        }
    }//GEN-LAST:event_btIngresarInicioActionPerformed

    private void LimpiarCajas() {
        this.txtCodigo.setText("");
        this.txtCantidad.setText("");
        this.txtNombre.setText("");
        this.txtPrecio.setText("");
        this.txtMinimo.setText("");
    }
    private void btUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUltimoActionPerformed
        try {
            if (!lista.listaVacia()) {
                this.txtCampoTexto.setText("El primer elemento es: \n" + (Productos) lista.getUltimo().getInformacion());
            } else {
                this.txtCampoTexto.setText("No hay elementos en la lista");
            }
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("Asegurese de haber creado la lista de elementos");
        }
    }//GEN-LAST:event_btUltimoActionPerformed

    private void btFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFrenteActionPerformed
        try {
            if (!lista.listaVacia()) {
                this.txtCampoTexto.setText("El primer elemento es: \n" + (Productos) lista.getInicio().getInformacion());
            } else {
                this.txtCampoTexto.setText("No hay elementos en la lista");
            }
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("Asegurese de haber creado la lista de elementos");
        }
    }//GEN-LAST:event_btFrenteActionPerformed

    private void btReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReporteActionPerformed
        try {
            if (!lista.listaVacia()) {
                this.txtCampoTexto.setText("Reporde de los productos:\n");
                Nodo aux = lista.getInicio();

                while (aux != null) {
                    this.txtCampoTexto.append("\n" + (Productos) aux.getInformacion());
                    aux = aux.getSiguiente();
                }
            } else {
                this.txtCampoTexto.setText("La lista de elementos esta vacia");
            }
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("Por favor cree la lista de elementos");
        }
    }//GEN-LAST:event_btReporteActionPerformed

//    try {
//            if (lista.listaVacia()) {
//                this.txtCampoTexto.setText("La lista de elementos esta vacia");
//            } else {
//                this.txtCampoTexto.setText("La lista de elementos no esta vacia");
//            }
//        } catch (NullPointerException e) {
//            this.txtCampoTexto.setText("Por favor cree la lista de elementos");
//        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btFrente;
    private javax.swing.JToggleButton btIngresarFinal;
    private javax.swing.JToggleButton btIngresarInicio;
    private javax.swing.JButton btIngresarPrueba;
    private javax.swing.JToggleButton btNElementos;
    private javax.swing.JToggleButton btReporte;
    private javax.swing.JToggleButton btRetirarInicio;
    private javax.swing.JToggleButton btUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpInicio;
    private javax.swing.JTextArea txtCampoTexto;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMinimo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
