/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import EstructuraPila.Notas;
import EstructuraPila.Pila;
import javax.swing.JOptionPane;

/**
 *
 * @author Armando Perugachi
 */
public class Ventana extends javax.swing.JFrame {

    Pila pila;
    Notas notas;

    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
//        pila = new Pila(10);
//        pila.Apilar(new Notas("100", "EDIS", 6, 7, 8));
//        pila.Apilar(new Notas("100", "POO", 8, 9, 0));
//        pila.Apilar(new Notas("100", "CVV", 5, 7, 9));
//        pila.Apilar(new Notas("200", "POO", 5, 8, 10));
//        pila.Apilar(new Notas("200", "EDIS", 6, 9, 0));
//        pila.Apilar(new Notas("300", "CVV", 6, 10, 0));
//        pila.Apilar(new Notas("300", "EDIS", 5, 7, 5));
//        pila.Apilar(new Notas("300", "RNAC", 10, 8, 0));
//        pila.Apilar(new Notas("400", "POO", 6, 6, 9));
//        pila.Apilar(new Notas("400", "EDIS", 4, 6, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTamañoPila = new javax.swing.JTextField();
        btCrearPila = new javax.swing.JButton();
        txtCodMateria = new javax.swing.JTextField();
        btApilar = new javax.swing.JToggleButton();
        btDesapilar = new javax.swing.JButton();
        btVacia = new javax.swing.JButton();
        btLlena = new javax.swing.JButton();
        btCima = new javax.swing.JButton();
        btNElementos = new javax.swing.JButton();
        txtNota1 = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtNota2 = new javax.swing.JTextField();
        txtNotaSupletorio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCampoTexto = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMateria1 = new javax.swing.JTextField();
        txtMateria3 = new javax.swing.JTextField();
        txtMateria2 = new javax.swing.JTextField();
        btPrueba = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 43, 62));
        jPanel1.setForeground(new java.awt.Color(9, 26, 47));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Estructura de datos pila");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Realizado por: Perugachi Luis");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese el tamaño de la Pila:");

        txtTamañoPila.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        btCrearPila.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btCrearPila.setText("Crear Pila");
        btCrearPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearPilaActionPerformed(evt);
            }
        });

        txtCodMateria.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        btApilar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btApilar.setText("Apilar");
        btApilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApilarActionPerformed(evt);
            }
        });

        btDesapilar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btDesapilar.setText("Desapilar");
        btDesapilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesapilarActionPerformed(evt);
            }
        });

        btVacia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btVacia.setText("Vacia");
        btVacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVaciaActionPerformed(evt);
            }
        });

        btLlena.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btLlena.setText("Llena");
        btLlena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLlenaActionPerformed(evt);
            }
        });

        btCima.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btCima.setText("Cima");
        btCima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCimaActionPerformed(evt);
            }
        });

        btNElementos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btNElementos.setText("Número de elementos");
        btNElementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNElementosActionPerformed(evt);
            }
        });

        txtNota1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        txtCedula.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        txtNota2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        txtNotaSupletorio.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        txtCampoTexto.setColumns(20);
        txtCampoTexto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtCampoTexto.setRows(5);
        jScrollPane1.setViewportView(txtCampoTexto);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cédula");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Código de Materia");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nota 1");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nota 2");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nota Supletorio");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton1.setText("Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Materia 1");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Materia 3");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Materia 2");

        txtMateria1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        txtMateria3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        txtMateria2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        btPrueba.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btPrueba.setText("Prueba");
        btPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPruebaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTamañoPila, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(btCrearPila, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btCima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btVacia, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btApilar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btDesapilar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btLlena, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(btNElementos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNota2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNota1)
                                            .addComponent(txtCodMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtNotaSupletorio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(138, 138, 138))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTamañoPila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCrearPila))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNotaSupletorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btApilar)
                            .addComponent(btDesapilar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btVacia)
                            .addComponent(btLlena))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNElementos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPrueba))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCrearPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearPilaActionPerformed
        try {
            int n = Integer.parseInt(this.txtTamañoPila.getText());

            if (n > 0) {
                pila = new Pila(n);
                this.txtCampoTexto.setText("Pila creada correctamente");
                vaciarCamposDeTextos();
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese un tamaño mayor a 0");
            }
        } catch (NumberFormatException e) {
            System.err.print("Error, " + e);
        }
    }//GEN-LAST:event_btCrearPilaActionPerformed

    private void btApilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApilarActionPerformed
        try {
            String cedula = this.txtCedula.getText();
            String codMateria = this.txtCodMateria.getText();
            double nota1 = Double.parseDouble(this.txtNota1.getText());
            double nota2 = Double.parseDouble(this.txtNota2.getText());
            double notaSupletorio = Double.parseDouble(this.txtNotaSupletorio.getText());

            notas = new Notas(cedula, codMateria, nota1, nota2, notaSupletorio);

            this.txtCampoTexto.setText(pila.Apilar(notas));

            vaciarCamposDeTextos();
        } catch (Exception e) {
            //this.txtCampoTexto.setText("No se encuentra creada la pila");
            System.err.print("Error, " + e);
        }
    }//GEN-LAST:event_btApilarActionPerformed

    private void btDesapilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesapilarActionPerformed
        try {
            notas = (Notas) pila.Desapilar();
            if (notas != null) {
                txtCampoTexto.setText("Nota\n" + "Cédula: " + notas.getCedula() + "\nCódigo de materia: " + notas.getCodMateria()
                        + "\nNota 1: " + notas.getNota1() + " Nota 2: " + notas.getNota2()
                        + "\nNota supletorio: " + notas.getNotaSupletorio() + "\nDesapilado correctamente");
            }
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("No se ecuentra creada la pila");
            System.err.print("Error, " + e);
        }
    }//GEN-LAST:event_btDesapilarActionPerformed

    private void btVaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVaciaActionPerformed
        try {
            if (pila.Vacia()) {
                this.txtCampoTexto.setText("La pila se ecuentra vacia");
            } else {
                this.txtCampoTexto.setText("La pila no se ecuentra vacia");
            }

        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("No se ecuentra creada la pila");
        }
    }//GEN-LAST:event_btVaciaActionPerformed

    private void btLlenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLlenaActionPerformed
        try {
            if (pila.Llena()) {
                this.txtCampoTexto.setText("La pila se ecuentra llena");
            } else {
                this.txtCampoTexto.setText("La pila no se ecuentra llena");
            }

        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("No se ecuentra creada la pila");
        }
    }//GEN-LAST:event_btLlenaActionPerformed

    private void btCimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCimaActionPerformed

        try {
            Notas cima = (Notas) pila.Cima();
            if (cima != null) {
                this.txtCampoTexto.setText("El elemento que esta en la cima de la pila es:\n"
                        + "Nota\n" + "Cédula: " + cima.getCedula() + "\nCódigo de materia: " + cima.getCodMateria()
                        + "\nNota 1: " + cima.getNota1() + " Nota 2: " + cima.getNota2()
                        + "\nNota supletorio: " + cima.getNotaSupletorio());
            }
        } catch (Exception e) {
            this.txtCampoTexto.setText("Error, " + e);
        }
    }//GEN-LAST:event_btCimaActionPerformed

    private void btNElementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNElementosActionPerformed
        try {
            int nElementos = pila.getnElementos();
            this.txtCampoTexto.setText("El numero de elementos de la pila es: " + nElementos);

        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("No se ecuentra creada la pila");
        }
    }//GEN-LAST:event_btNElementosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (pila.getnElementos() > 0) {
                String reporte = "";

                Pila pilaAux = new Pila(pila.getnElementos());
                Notas n;
                while (!pila.Vacia()) {
                    n = (Notas) pila.Desapilar();
                    reporte += "\n----------------\nCédula: " + n.getCedula() + "   Código de materia: " + n.getCodMateria()
                            + "\nNota 1: " + n.getNota1() + "    Nota 2: "
                            + n.getNota2() + "\nNota supletorio: " + n.getNotaSupletorio();
                    pilaAux.Apilar(n);
                }

                while (!pilaAux.Vacia()) {
                    pila.Apilar(pilaAux.Desapilar());
                }
                this.txtCampoTexto.setText(reporte);
            }
        } catch (Exception e) {
            System.err.print("Error," + e);
            this.txtCampoTexto.setText("No se encuentra la pila creada");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPruebaActionPerformed
        try {
            Pila aprobados = Aprobados();
            String materia1 = this.txtMateria1.getText();
            String materia2 = this.txtMateria2.getText();
            String materia3 = this.txtMateria3.getText();
            Notas notas;
            int n1 = 0;
            int n2 = 0;
            int n3 = 0;

            while (!aprobados.Vacia()) {
                notas = (Notas) aprobados.Desapilar();
                if (notas.getCodMateria().equals(materia1)) {
                    n1++;
                } else if (notas.getCodMateria().equals(materia2)) {
                    n2++;
                } else if (notas.getCodMateria().equals(materia3)) {
                    n3++;
                }
            }

            if ((n1 >= n2) && (n1 >= n3)) {
                this.txtCampoTexto.setText("El número mayor de aprobados es " + n1 + " en la materia de: " + materia1);
            } else if ((n2 >= n1) && (n2 >= n3)) {
                this.txtCampoTexto.setText("El número mayor de aprobados es " + n2 + " en la materia de: " + materia2);
            } else if ((n3 >= n1) && (n3 >= n2)) {
                this.txtCampoTexto.setText("El número mayor de aprobados es " + n3 + " en la materia de: " + materia3);
            }
        } catch (Exception e) {
            this.txtCampoTexto.setText("Porfavor verifica si la pila esta creada");
            System.err.print("Error, " + e);
        }
    }//GEN-LAST:event_btPruebaActionPerformed

    private Pila Aprobados() {
        Pila pAprobados = new Pila(pila.getnElementos());
        Pila pAux = new Pila(pila.getnElementos());
        Notas notas;

        while (!pila.Vacia()) {
            notas = (Notas) pila.Cima();
            if ((notas.getNota1() + notas.getNota2()) >= 14
                    || (notas.getNota1() + notas.getNota2() + notas.getNotaSupletorio()) >= 21) {
                pAprobados.Apilar(notas);
            }
            pAux.Apilar(pila.Desapilar());
        }

        while (!pAux.Vacia()) {
            pila.Apilar(pAux.Desapilar());
        }

        return pAprobados;
    }

    private void vaciarCamposDeTextos() {
        this.txtTamañoPila.setText("");
        this.txtCedula.setText("");
        this.txtCodMateria.setText("");
        this.txtNota1.setText("");
        this.txtNotaSupletorio.setText("");
        this.txtNota2.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btApilar;
    private javax.swing.JButton btCima;
    private javax.swing.JButton btCrearPila;
    private javax.swing.JButton btDesapilar;
    private javax.swing.JButton btLlena;
    private javax.swing.JButton btNElementos;
    private javax.swing.JButton btPrueba;
    private javax.swing.JButton btVacia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtCampoTexto;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodMateria;
    private javax.swing.JTextField txtMateria1;
    private javax.swing.JTextField txtMateria2;
    private javax.swing.JTextField txtMateria3;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNotaSupletorio;
    private javax.swing.JTextField txtTamañoPila;
    // End of variables declaration//GEN-END:variables
}
