/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cuadrado_magico;

import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Kevin
 */
public class Principal extends javax.swing.JFrame {

    private JTextField[][] entradas;
    CuadradoMagico cuadradoMagico;

    /**
     * Creates new form Principal
     */
    public Principal() {

        this.getContentPane().setBackground(new Color(22, 39, 65));

        //panel_1.setBackground(Color.WHITE);
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_1 = new javax.swing.JPanel();
        btn_crear = new javax.swing.JButton();
        txt_tamaño = new javax.swing.JTextField();
        btn_comprobar = new javax.swing.JButton();
        btn_llenar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuadrado Magico");

        panel_1.setBackground(new java.awt.Color(22, 39, 60));

        javax.swing.GroupLayout panel_1Layout = new javax.swing.GroupLayout(panel_1);
        panel_1.setLayout(panel_1Layout);
        panel_1Layout.setHorizontalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        panel_1Layout.setVerticalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        btn_crear.setBackground(new java.awt.Color(0, 102, 102));
        btn_crear.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        btn_crear.setForeground(new java.awt.Color(255, 255, 255));
        btn_crear.setText("Crear");
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });

        txt_tamaño.setText("3");

        btn_comprobar.setBackground(new java.awt.Color(0, 102, 102));
        btn_comprobar.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        btn_comprobar.setForeground(new java.awt.Color(255, 255, 255));
        btn_comprobar.setText("Comprobar");
        btn_comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comprobarActionPerformed(evt);
            }
        });

        btn_llenar.setBackground(new java.awt.Color(0, 102, 102));
        btn_llenar.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        btn_llenar.setForeground(new java.awt.Color(255, 255, 255));
        btn_llenar.setText("Llenar");
        btn_llenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_llenarActionPerformed(evt);
            }
        });

        btn_limpiar.setBackground(new java.awt.Color(0, 102, 102));
        btn_limpiar.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        btn_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btn_crear)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btn_comprobar)
                        .addGap(29, 29, 29)
                        .addComponent(btn_llenar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_limpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crear)
                    .addComponent(txt_tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_comprobar)
                    .addComponent(btn_llenar)
                    .addComponent(btn_limpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Crear_cuadrado() {
        Font fuente = new Font("Dialog", Font.BOLD, 15);
        int tamaño = Integer.parseInt(txt_tamaño.getText());
        if (tamaño % 2 != 0 && tamaño > 0) {
            cuadradoMagico = new CuadradoMagico(tamaño);

            entradas = new JTextField[tamaño][tamaño];
            int x = 10;
            int y = 10;
            for (int i = 0; i < entradas.length; i++) {
                for (int j = 0; j < entradas.length; j++) {
                    entradas[i][j] = new JTextField(" 0 ");
                    entradas[i][j].setBounds(x, y, 35, 35);
                    entradas[i][j].setFont(fuente);
//                    entradas[i][j].setVisible(true);

                    entradas[i][j].setForeground(new Color(22, 123, 113));
                    panel_1.add(entradas[i][j]);
                    x += 40;

                }
                y += 40;
                x = 10;
            }
            //cuadradoMagico.Imprimir();
        } else {
            JOptionPane.showMessageDialog(null, "Tienes que ingresar un numero positivo e impar");
        }
    }

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
        // TODO add your handling code here:
        try {
            if (entradas == null) {
                Crear_cuadrado();
            } else {
                for (int i = 0; i < entradas.length; i++) {
                    for (int j = 0; j < entradas.length; j++) {
                        entradas[i][j].setVisible(false);

                    }
                }
                Crear_cuadrado();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese la cantidad");
        }


    }//GEN-LAST:event_btn_crearActionPerformed

    public void Limpiar() {
        for (int i = 0; i < cuadradoMagico.getTamaño(); i++) {
            for (int j = 0; j < cuadradoMagico.getTamaño(); j++) {
                entradas[i][j].setText("0");
                entradas[i][j].update(entradas[i][j].getGraphics());
            }
        }
    }

    private void btn_comprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comprobarActionPerformed
        // TODO add your handling code here:
        int tamaño = Integer.parseInt(txt_tamaño.getText());
        try {
            boolean aux = true;
            if (entradas != null) {
                for (int i = 0; i < tamaño; i++) {
                    for (int j = 0; j < tamaño; j++) {

                        if (cuadradoMagico.getValor(i, j) == Integer.valueOf(entradas[i][j].getText().trim())) {
                        } else {
                            aux = false;
                            break;
                        }
                    }
                }

                if (aux) {

                    JOptionPane.showMessageDialog(null, "¡Felicidades! ... Solucionaste de Cuadrado Magico ");
                } else {
                    JOptionPane.showMessageDialog(null, "Aun no......... Sigue intentando");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Aun no haz creado el cuadrado magico");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Rellene todas las casillas de manera correcta");
        }


    }//GEN-LAST:event_btn_comprobarActionPerformed

    private void btn_llenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_llenarActionPerformed
        // TODO add your handling code here:
        Limpiar();

        if (entradas != null) {
            cuadradoMagico.Crear_Cuadrado(entradas);
        } else {
            JOptionPane.showMessageDialog(null, "Aun no haz creado el cuadrado magico");
        }


    }//GEN-LAST:event_btn_llenarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_comprobar;
    private javax.swing.JButton btn_crear;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_llenar;
    private javax.swing.JPanel panel_1;
    private javax.swing.JTextField txt_tamaño;
    // End of variables declaration//GEN-END:variables
}
