/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import javax.swing.JOptionPane;

/**
 *
 * @author Armando Perugachi
 */
public class AppCoordenadas extends javax.swing.JFrame {

    CoordenadasPolares cP1;

    /**
     * Creates new form NewJFrame
     */
    public AppCoordenadas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbInfo = new javax.swing.JLabel();
        lbInfo1 = new javax.swing.JLabel();
        lbInfo2 = new javax.swing.JLabel();
        tfAngulo = new javax.swing.JTextField();
        tfPolar = new javax.swing.JTextField();
        btAsignar = new javax.swing.JButton();
        btCos = new javax.swing.JButton();
        btSen = new javax.swing.JButton();
        btRectangular = new javax.swing.JButton();
        lbSen = new javax.swing.JLabel();
        lbCos = new javax.swing.JLabel();
        lbRectangular = new javax.swing.JLabel();
        btRadian = new javax.swing.JButton();
        lbRadian = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setText("Coordenadas Polares");
        getContentPane().add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        lbInfo.setText("Digite las coordenadas polares");
        getContentPane().add(lbInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        lbInfo1.setText("Angulo");
        getContentPane().add(lbInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        lbInfo2.setText("Coordenada polar R");
        getContentPane().add(lbInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, 20));

        tfAngulo.setText("6");
        getContentPane().add(tfAngulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 40, -1));

        tfPolar.setText("57");
        getContentPane().add(tfPolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 40, -1));

        btAsignar.setText("Asignar");
        btAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAsignarActionPerformed(evt);
            }
        });
        getContentPane().add(btAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        btCos.setText("Calcular Coseno");
        btCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCosActionPerformed(evt);
            }
        });
        getContentPane().add(btCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        btSen.setText("Calcular Seno");
        btSen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSenActionPerformed(evt);
            }
        });
        getContentPane().add(btSen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        btRectangular.setText("Calcular Coordenada Rectangular");
        btRectangular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRectangularActionPerformed(evt);
            }
        });
        getContentPane().add(btRectangular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));
        getContentPane().add(lbSen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 90, 20));
        getContentPane().add(lbCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 90, 20));
        getContentPane().add(lbRectangular, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 90, 20));

        btRadian.setText("Radian");
        btRadian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRadianActionPerformed(evt);
            }
        });
        getContentPane().add(btRadian, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));
        getContentPane().add(lbRadian, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 90, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAsignarActionPerformed
        double angulo, r;

        if (tfAngulo.getText().equals("") || tfPolar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Asigne Valores");
        } else {

            angulo = Double.parseDouble(tfAngulo.getText());
            r = Double.parseDouble(tfPolar.getText());

            if (cP1 != null) {
                cP1.setAngulo(angulo);
                cP1.setR(r);
            } else {
                cP1 = new CoordenadasPolares(angulo, r);
            }
        }
    }//GEN-LAST:event_btAsignarActionPerformed

    private void btSenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSenActionPerformed
        lbSen.setText(String.valueOf(cP1.senoX()));
    }//GEN-LAST:event_btSenActionPerformed

    private void btCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCosActionPerformed
        lbCos.setText(String.valueOf(cP1.cosX()));
    }//GEN-LAST:event_btCosActionPerformed

    private void btRectangularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRectangularActionPerformed
        lbRectangular.setText(String.valueOf(cP1.Transformar().Imprimir()));
    }//GEN-LAST:event_btRectangularActionPerformed

    private void btRadianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRadianActionPerformed
        lbRadian.setText(String.valueOf(cP1.Radian()));
    }//GEN-LAST:event_btRadianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppCoordenadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppCoordenadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppCoordenadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppCoordenadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppCoordenadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAsignar;
    private javax.swing.JButton btCos;
    private javax.swing.JButton btRadian;
    private javax.swing.JButton btRectangular;
    private javax.swing.JButton btSen;
    private javax.swing.JLabel lbCos;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbInfo1;
    private javax.swing.JLabel lbInfo2;
    private javax.swing.JLabel lbRadian;
    private javax.swing.JLabel lbRectangular;
    private javax.swing.JLabel lbSen;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField tfAngulo;
    private javax.swing.JTextField tfPolar;
    // End of variables declaration//GEN-END:variables
}
