/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ImageIcon;

/**
 *
 * @author Armando Perugachi
 */
public class Ejercicio2 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio2
     */
    final ImageIcon baloncesto = new ImageIcon(getClass().getResource("/Imagenes/1.jpg"));
    final ImageIcon tenis = new ImageIcon(getClass().getResource("/Imagenes/2.jpg"));
    final ImageIcon futbol = new ImageIcon(getClass().getResource("/Imagenes/3.jpg"));
    final ImageIcon natacion = new ImageIcon(getClass().getResource("/Imagenes/4.jpg"));

    public Ejercicio2() {
        initComponents();
        btGrupo.add(btTenis);
        btGrupo.add(btBaloncesto);
        btGrupo.add(btFutbol);
        btGrupo.add(btNatacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGrupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btNatacion = new javax.swing.JRadioButton();
        btFutbol = new javax.swing.JRadioButton();
        btBaloncesto = new javax.swing.JRadioButton();
        btTenis = new javax.swing.JRadioButton();
        lbDeporte = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Escoge tu deporte favorito");

        btNatacion.setText("Natacion");
        btNatacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNatacionActionPerformed(evt);
            }
        });

        btFutbol.setText("Futbol");
        btFutbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFutbolActionPerformed(evt);
            }
        });

        btBaloncesto.setText("Baloncesto");
        btBaloncesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBaloncestoActionPerformed(evt);
            }
        });

        btTenis.setText("Tenis");
        btTenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTenisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btTenis)
                            .addComponent(btBaloncesto)
                            .addComponent(btFutbol)
                            .addComponent(btNatacion))
                        .addGap(201, 201, 201)
                        .addComponent(lbDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btNatacion)
                        .addGap(31, 31, 31)
                        .addComponent(btFutbol)
                        .addGap(26, 26, 26)
                        .addComponent(btBaloncesto)
                        .addGap(30, 30, 30)
                        .addComponent(btTenis))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFutbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFutbolActionPerformed
        if (this.btFutbol.isSelected()) {
            this.lbDeporte.setIcon(futbol);
        }
    }//GEN-LAST:event_btFutbolActionPerformed

    private void btBaloncestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBaloncestoActionPerformed
        if (this.btBaloncesto.isSelected()) {
            this.lbDeporte.setIcon(baloncesto);
        }
    }//GEN-LAST:event_btBaloncestoActionPerformed

    private void btNatacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNatacionActionPerformed
        if (this.btNatacion.isSelected()) {
            this.lbDeporte.setIcon(natacion);
        }
    }//GEN-LAST:event_btNatacionActionPerformed

    private void btTenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTenisActionPerformed
        if (this.btTenis.isSelected()) {
            this.lbDeporte.setIcon(tenis);
        }
    }//GEN-LAST:event_btTenisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btBaloncesto;
    private javax.swing.JRadioButton btFutbol;
    private javax.swing.ButtonGroup btGrupo;
    private javax.swing.JRadioButton btNatacion;
    private javax.swing.JRadioButton btTenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDeporte;
    // End of variables declaration//GEN-END:variables
}
