/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulario;

import EstructuraCola.Cola;
import EstructuraCola.Productos;
import EstructuraPila.Pila;
import javax.swing.JOptionPane;

/**
 *
 * @author Armando Perugachi
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Cola cola;
    Productos productos;

    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        cola = new Cola(6);

        cola.Ingresar(new Productos("TVS40", "TELEVISOR LED SONY DE 40 PULGADAS", 7, 650.00, 2));
        cola.Ingresar(new Productos("PARJBL15", "PARLANTE AMPLIFICADO JBL DE 15 PULGADAS", 8, 369.00, 2));
        cola.Ingresar(new Productos("MICPAN", "MICROONDAS PANASONIC", 9, 225.00, 3));
        cola.Ingresar(new Productos("LICO3V", "LICUADORA OSTER 3 VELOCIDADES", 12, 99.00, 3));
        cola.Ingresar(new Productos("COCIND5", "COCINA INDURAMA 5 QUEMADORES", 5, 589.00, 3));
        cola.Ingresar(new Productos("TVTCL40", "TELEVISOR LED TCL DE 40 PULGADAS", 12, 399.00, 4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTamañoCola = new javax.swing.JTextField();
        btCrearPila = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtMinimo = new javax.swing.JTextField();
        btVacia = new javax.swing.JToggleButton();
        btNElementos = new javax.swing.JToggleButton();
        btRetirar = new javax.swing.JToggleButton();
        btIngresar = new javax.swing.JToggleButton();
        btLlena = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCampoTexto = new javax.swing.JTextArea();
        btReporte = new javax.swing.JToggleButton();
        btFrente = new javax.swing.JToggleButton();
        btVender = new javax.swing.JToggleButton();
        btComprar = new javax.swing.JToggleButton();
        btExamen = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Estructura de datos pila");
        jpInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Realizado por: Perugachi Luis");
        jpInicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Ingrese el tamaño de la Cola:");
        jpInicio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtTamañoCola.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jpInicio.add(txtTamañoCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 60, -1));

        btCrearPila.setBackground(new java.awt.Color(247, 246, 251));
        btCrearPila.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btCrearPila.setText("Crear Cola");
        btCrearPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearPilaActionPerformed(evt);
            }
        });
        jpInicio.add(btCrearPila, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 140, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Nombre: ");
        jpInicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Precio: ");
        jpInicio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Código: ");
        jpInicio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Mínimo: ");
        jpInicio.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Cantidad: ");
        jpInicio.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jpInicio.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 260, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jpInicio.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 260, -1));

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jpInicio.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 260, -1));

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jpInicio.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 260, -1));

        txtMinimo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jpInicio.add(txtMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 260, -1));

        btVacia.setBackground(new java.awt.Color(247, 246, 251));
        btVacia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btVacia.setText("Vacia");
        btVacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVaciaActionPerformed(evt);
            }
        });
        jpInicio.add(btVacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 90, -1));

        btNElementos.setBackground(new java.awt.Color(247, 246, 251));
        btNElementos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btNElementos.setText("Número de elementos ");
        btNElementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNElementosActionPerformed(evt);
            }
        });
        jpInicio.add(btNElementos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        btRetirar.setBackground(new java.awt.Color(247, 246, 251));
        btRetirar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btRetirar.setText("Retirar");
        btRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetirarActionPerformed(evt);
            }
        });
        jpInicio.add(btRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 90, -1));

        btIngresar.setBackground(new java.awt.Color(247, 246, 251));
        btIngresar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btIngresar.setText("Ingresar");
        btIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarActionPerformed(evt);
            }
        });
        jpInicio.add(btIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        btLlena.setBackground(new java.awt.Color(247, 246, 251));
        btLlena.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btLlena.setText("Llena");
        btLlena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLlenaActionPerformed(evt);
            }
        });
        jpInicio.add(btLlena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 90, -1));

        txtCampoTexto.setColumns(20);
        txtCampoTexto.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtCampoTexto.setRows(5);
        jScrollPane1.setViewportView(txtCampoTexto);

        jpInicio.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 370, 230));

        btReporte.setBackground(new java.awt.Color(247, 246, 251));
        btReporte.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btReporte.setText("Reporte");
        btReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReporteActionPerformed(evt);
            }
        });
        jpInicio.add(btReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 90, -1));

        btFrente.setBackground(new java.awt.Color(247, 246, 251));
        btFrente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btFrente.setText("Frente");
        btFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFrenteActionPerformed(evt);
            }
        });
        jpInicio.add(btFrente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 90, -1));

        btVender.setBackground(new java.awt.Color(247, 246, 251));
        btVender.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btVender.setText("Vender");
        btVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVenderActionPerformed(evt);
            }
        });
        jpInicio.add(btVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 90, -1));

        btComprar.setBackground(new java.awt.Color(247, 246, 251));
        btComprar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btComprar.setText("Comprar");
        btComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprarActionPerformed(evt);
            }
        });
        jpInicio.add(btComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 190, -1));

        btExamen.setBackground(new java.awt.Color(247, 246, 251));
        btExamen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btExamen.setText("Examen");
        btExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExamenActionPerformed(evt);
            }
        });
        jpInicio.add(btExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 90, -1));

        getContentPane().add(jpInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCrearPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearPilaActionPerformed
        try {
            int tamaño = Integer.parseInt(this.txtTamañoCola.getText());
            cola = new Cola(tamaño);
            this.txtCampoTexto.setText("Se ha creado correctamente la cola");
        } catch (NumberFormatException e) {
            this.txtCampoTexto.setText("Por favor digite un número para crear la cola");
        } catch (NegativeArraySizeException e) {
            this.txtCampoTexto.setText("No se admite numeros negativos");
        }
    }//GEN-LAST:event_btCrearPilaActionPerformed

    private void btVaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVaciaActionPerformed
        try {
            if (cola.Vacia()) {
                this.txtCampoTexto.setText("La cola esta vacia");
            } else {
                this.txtCampoTexto.setText("La cola no esta vacia");
            }
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("Por favor cree la cola de elementos");
        }
    }//GEN-LAST:event_btVaciaActionPerformed

    private void btNElementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNElementosActionPerformed
        try {
            this.txtCampoTexto.setText("El numero de elementos de la cola es: " + cola.getnElementos());
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("Por favor asegurese de crear la cola");
        }
    }//GEN-LAST:event_btNElementosActionPerformed

    private void btRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetirarActionPerformed
        try {
            productos = (Productos) cola.Retirar();

            if (productos != null) {
                this.txtCampoTexto.setText("Se ha retirado el producto:"
                        + "\n" + productos);
            } else {
                this.txtCampoTexto.setText("No se encontro elementos en la cola");
            }
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("No se encontro elementos en la cola");
        }
    }//GEN-LAST:event_btRetirarActionPerformed

    private void btIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarActionPerformed
        try {
            String codigo = this.txtCodigo.getText();
            String nombre = this.txtNombre.getText();
            int cantidad = Integer.valueOf(this.txtCantidad.getText());
            double precio = Double.parseDouble(this.txtPrecio.getText());
            int minimo = Integer.parseInt(this.txtMinimo.getText());
            productos = new Productos(codigo, nombre, cantidad, precio, minimo);

            if (!cola.Llena()) {
                LimpiarCajas();
            }
            this.txtCampoTexto.setText(cola.Ingresar(productos));
        } catch (NumberFormatException e) {
            this.txtCampoTexto.setText("Por favor digite un número\nen los campos cantidad, precio, mínimo");
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("Por favor cree la cola para ingresar elementos");
        }
    }//GEN-LAST:event_btIngresarActionPerformed

    private void LimpiarCajas() {
        this.txtCodigo.setText("");
        this.txtCantidad.setText("");
        this.txtNombre.setText("");
        this.txtPrecio.setText("");
        this.txtMinimo.setText("");
    }
    private void btLlenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLlenaActionPerformed
        try {
            if (cola.Llena()) {
                this.txtCampoTexto.setText("La cola esta llena");
            } else {
                this.txtCampoTexto.setText("La cola no esta llena");
            }
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("Por favor cree la cola de elementos");
        }
    }//GEN-LAST:event_btLlenaActionPerformed

    private void btReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReporteActionPerformed
        try {
            if (!cola.Vacia()) {
                Cola aux = new Cola(cola.getnElementos());
                this.txtCampoTexto.setText("Reporte de los productos: ");
                while (!cola.Vacia()) {
                    productos = (Productos) cola.Frente();
                    this.txtCampoTexto.append("\n" + productos);

                    aux.Ingresar(cola.Retirar());
                }

                while (!aux.Vacia()) {
                    cola.Ingresar(aux.Retirar());
                }
            } else {
                this.txtCampoTexto.setText("No se encontro elementos en la cola");
            }
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("Asegurese de haber creado la cola de elementos");
        }
    }//GEN-LAST:event_btReporteActionPerformed

    private void btFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFrenteActionPerformed
        try {
            productos = (Productos) cola.Frente();

            if (productos != null) {
                this.txtCampoTexto.setText("El elemento que esta en frente es:"
                        + "\n" + productos);
            } else {
                this.txtCampoTexto.setText("No se encontro elementos en la cola");
            }
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("No se encontra creada la cola");
        }
    }//GEN-LAST:event_btFrenteActionPerformed

    private void btVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVenderActionPerformed
        try {
            String codigo = this.txtCodigo.getText();
            int cantidad = Integer.valueOf(this.txtCantidad.getText());

            if (!cola.Vacia()) {
                Cola aux = new Cola(cola.getnElementos());

                while (!cola.Vacia()) {
                    productos = (Productos) cola.Frente();
                    if (productos.getCodigo().equals(codigo)) {
                        if ((productos.getCantidad() - cantidad) > 0) {
                            if (JOptionPane.showConfirmDialog(null, "Esta seguro de vender\n" + cantidad + " " + productos.getNombre() + "s") == 0) {
                                productos.setCantidad(productos.getCantidad() - cantidad);
                                this.txtCampoTexto.setText("Se ha vendido: " + cantidad + " " + productos.getNombre() + "s"
                                        + "\n" + productos);
                            } else {
                                this.txtCampoTexto.setText("Ha cancelado la venta del producto");
                            }
                        } else {
                            this.txtCampoTexto.setText("Ya no se dispone de producto en el inventario"
                                    + "\nProducto disponible: " + productos.getCantidad());
                        }
                        while (!cola.Vacia()) {
                            aux.Ingresar(cola.Retirar());
                        }
                    } else {
                        this.txtCampoTexto.setText("No se econtro ningun producto con el código digitado");
                    }
                    aux.Ingresar(cola.Retirar());
                }

                while (!aux.Vacia()) {
                    cola.Ingresar(aux.Retirar());
                }
            } else {
                this.txtCampoTexto.setText("No se encontro elementos en la cola");
            }

        } catch (NumberFormatException e) {
            this.txtCampoTexto.setText("Por favor digite un número en la cantidad");
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("Por favor cree la cola para ingresar elementos");
        }
    }//GEN-LAST:event_btVenderActionPerformed

    private void btComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprarActionPerformed
        try {
            String codigo = this.txtCodigo.getText();
            int cantidad = Integer.valueOf(this.txtCantidad.getText());

            if (!cola.Vacia()) {
                Cola aux = new Cola(cola.getnElementos());

                while (!cola.Vacia()) {
                    productos = (Productos) cola.Frente();
                    if (productos.getCodigo().equals(codigo)) {
                        productos.setCantidad(cantidad + productos.getCantidad());
                        this.txtCampoTexto.setText("Se ha comprado " + cantidad + " " + productos.getNombre() + "s"
                                + "\n" + productos);
                        while (!cola.Vacia()) {
                            aux.Ingresar(cola.Retirar());
                        }
                    } else {
                        this.txtCampoTexto.setText("No se econtro ningun producto con el codigo digitado");
                    }
                    aux.Ingresar(cola.Retirar());
                }

                while (!aux.Vacia()) {
                    cola.Ingresar(aux.Retirar());
                }
            } else {
                this.txtCampoTexto.setText("No se encontro elementos en la cola");
            }

//            if (!cola.Llena()) {
//                LimpiarCajas();
//            }
//            
        } catch (NumberFormatException e) {
            this.txtCampoTexto.setText("Por favor digite un número en la cantidad");
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("Por favor cree la cola para ingresar elementos");
        }
    }//GEN-LAST:event_btComprarActionPerformed

    private void btExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExamenActionPerformed
        try {
            Pila pElementos = new Pila(cola.getnElementos());
            Pila pAux = new Pila(cola.getnElementos());

            while (!cola.Vacia()) {
                if (pElementos.Vacia()) {
                    pElementos.Apilar(cola.Retirar());

                } else if (((Productos) cola.Frente()).getPrecio() <= ((Productos) pElementos.Cima()).getPrecio()) {
                    pElementos.Apilar(cola.Retirar());

                } else if (((Productos) cola.Frente()).getPrecio() > ((Productos) pElementos.Cima()).getPrecio()) {

                    while (!pElementos.Vacia() && ((Productos) cola.Frente()).getPrecio() > ((Productos) pElementos.Cima()).getPrecio()) {
                        pAux.Apilar(pElementos.Desapilar());
                    }
                    pElementos.Apilar(cola.Retirar());

                    while (!pAux.Vacia()) {
                        pElementos.Apilar(pAux.Desapilar());
                    }
                }
            }

            while (!pElementos.Vacia()) {
                cola.Ingresar(pElementos.Desapilar());
            }
            
        } catch (NullPointerException e) {
            this.txtCampoTexto.setText("Por favor asegurese de haber creado la cola de elementos");
        }
    }//GEN-LAST:event_btExamenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btComprar;
    private javax.swing.JButton btCrearPila;
    private javax.swing.JToggleButton btExamen;
    private javax.swing.JToggleButton btFrente;
    private javax.swing.JToggleButton btIngresar;
    private javax.swing.JToggleButton btLlena;
    private javax.swing.JToggleButton btNElementos;
    private javax.swing.JToggleButton btReporte;
    private javax.swing.JToggleButton btRetirar;
    private javax.swing.JToggleButton btVacia;
    private javax.swing.JToggleButton btVender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpInicio;
    private javax.swing.JTextArea txtCampoTexto;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMinimo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTamañoCola;
    // End of variables declaration//GEN-END:variables
}
